# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-09-13 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminationResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examination_time', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(choices=[('Healthy', 'Healthy'), ('Corona', 'Corona'), ('Botism', 'Botism'), ('Dead', 'Dead')], default='Botism', max_length=7)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='hospital.Patient')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='hospital.Worker')),
            ],
        ),
        migrations.RemoveField(
            model_name='examineresult',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='examineresult',
            name='worker',
        ),
        migrations.AlterField(
            model_name='department',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='hospital.Hospital'),
        ),
        migrations.DeleteModel(
            name='ExamineResult',
        ),
    ]
